### ISSUE TITLE
Automatically sync on a regular, configurable schedule

### ISSUE THREAD

**Issue by joshjhall** [getmatterapp/roam-matter#4]
Would be convenient to set a regular sync interval (e.g., once a day, once every 4hrs, once a week, etc.). Doesn't need to be crontab flexible by any stretch, just some simple scheduling to pull in content a few times a day from Matter would be sufficient. Could even be really simple in the configuration with a toggle to either automatically sync (i.e., every 4hrs) or only manually sync. That'd probably be sufficient for most users (I'm guessing, but it's an educated guess). Would certainly be enough for my personal needs.

**Comment by hunterclarke** [comment]
@joshjhall In the settings we already allow you to configure a "Sync Frequency." Are you looking for anything in addition to what the plugin provides there?

**Comment by hunterclarke** [comment]
I think the sync frequency setting in the plugin settings is what you're looking for. If I'm mistaken, feel free to re-open and clarify.
